name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up .env and export vars to GITHUB_ENV
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
        while IFS= read -r line; do
          echo "$line" >> $GITHUB_ENV
        done < .env
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test -- --test-threads=1
