name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check if .env file exists
      run: |
          if [ -f .env ]; then
            echo ".env file exists"
          else
            echo "${{secrets.ENV_FILE}}" > .env
            echo "created .env file"
          fi
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test -- --test-threads=1
